language: generic
sudo: false
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
matrix:
  include:
    - env: BUILD=cabal GHC=8.0.2 CABAL=2.0
      compiler: "cabal@8.0.2"
      addons: {apt: {sources: [hvr-ghc], packages: [ghc-8.0.2, cabal-install-2.0]}}
    - env: BUILD=cabal GHC=7.10.3 CABAL=1.24
      compiler: "cabal@7.10.3"
      addons: {apt: {sources: [hvr-ghc], packages: [ghc-7.10.3, cabal-install-1.24]}}
    - env: BUILD=stack GHC=8.0.2
      compiler: "stack@8.0.2"
    - env: BUILD=stack GHC=7.10.3 ARG="--resolver=lts-6"
      compiler: "stack@7.10.3"
before_install:
  - case "$BUILD" in
      cabal)
        export PATH=/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:$PATH;;
      stack)
        export PATH=/opt/ghc/$GHC/bin:$PATH;
        mkdir -p ~/.local/bin;
        export PATH=~/.local/bin:$PATH;
        travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack;
        chmod a+x ~/.local/bin/stack;
        stack config set system-ghc --global true;;
    esac
script:
  - set -e; case "$BUILD" in
      cabal)
        cabal sandbox init;
        travis_retry cabal update;
        cabal install;
        cabal configure --enable-tests --enable-benchmarks -v2 --ghc-options="-Wall -Werror";
        cabal build;
        cabal test;
        cabal check;
        mkdir -p dist;
        cabal sdist --builddir=dist;
        cd dist;
        cabal install $(find $PWD -name "*.tar.gz");;
      stack)
        stack setup $ARG --no-terminal --no-haddock --no-haddock-deps;
        stack build $ARG --no-terminal --no-haddock --no-haddock-deps --pedantic;
        stack test $ARG --no-terminal --no-haddock --no-haddock-deps;;
    esac
