language: generic
sudo: required

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack

before_install:
 - curl -sSL https://get.haskellstack.org/ | sh

script:
 - stack setup
 - stack build
